# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e41de83df8c1bff38ffb4d09d70584a8955565cb0a911096108c0157464c38644b78123c5bf4614c4a5cd4e2e1feaa4572c02e75b65ad05f50270898daebb90

test:
  secret_key_base: d6ccfd87bdefb8f1c732e0a2befe3b170cbb9cc24a6bf2682a30280d8160d51700ba59010f8c1eb9c4c4aba2dcb8dcd29110ceead8fb8df3c01deabfed9ec1eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
